// .github/scripts/comment.js
import { Octokit } from "@octokit/rest";

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

async function run() {
  const prNumber = process.env.PR_NUMBER;
  const repo = process.env.GITHUB_REPOSITORY.split("/")[1];
  const owner = process.env.GITHUB_REPOSITORY.split("/")[0];

  const aiReport = process.env.AI_REPORT || "No AI review available.";
  const securityReport = process.env.SECURITY_REPORT || "No security issues detected.";
  const previewUrl = process.env.PREVIEW_URL || "";

  let body = `## 🤖 AI Code Review\n\n${aiReport}\n\n`;

  body += `## 🔐 Security Scan\n\n${securityReport}\n\n`;

  if (previewUrl) {
    body += `## 🌐 Live Preview\n\n**Test this PR here:** [Preview #${prNumber}](${previewUrl})\n\n`;
  }

  body += `---\n*Generated by Fancy Widget PR Agent*`;

  try {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });

    console.log("✅ Comment posted successfully.");
  } catch (error) {
    console.error("❌ Failed to post comment:", error.message);
    process.exit(1);
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
